import type { MerchantRule } from '@/types/finance';
import { generateId } from '@/lib/utils/date';
import { CAT_IDS } from './categories';

const now = new Date().toISOString();

function rule(pattern: string, categoryId: string): MerchantRule {
  return {
    id: generateId(),
    pattern,
    isRegex: false,
    categoryId,
    source: 'system',
    matchCount: 0,
    createdAt: now,
    updatedAt: now,
  };
}

export const DEFAULT_MERCHANT_RULES: MerchantRule[] = [
  // ── Streaming / Subscriptions ──────────────────────────────────────────────
  rule('netflix',           CAT_IDS.SUBSCRIPTIONS),
  rule('spotify',           CAT_IDS.SUBSCRIPTIONS),
  rule('amazon prime',      CAT_IDS.SUBSCRIPTIONS),
  rule('disney+',           CAT_IDS.SUBSCRIPTIONS),
  rule('disney plus',       CAT_IDS.SUBSCRIPTIONS),
  rule('youtube premium',   CAT_IDS.SUBSCRIPTIONS),
  rule('sky subscription',  CAT_IDS.SUBSCRIPTIONS),
  rule('now tv',            CAT_IDS.SUBSCRIPTIONS),
  rule('binge',             CAT_IDS.SUBSCRIPTIONS),
  rule('stan ',             CAT_IDS.SUBSCRIPTIONS),
  rule('paramount+',        CAT_IDS.SUBSCRIPTIONS),
  rule('apple.com/bill',    CAT_IDS.SUBSCRIPTIONS),
  rule('google one',        CAT_IDS.SUBSCRIPTIONS),
  rule('microsoft 365',     CAT_IDS.SUBSCRIPTIONS),
  rule('dropbox',           CAT_IDS.SUBSCRIPTIONS),
  rule('adobe',             CAT_IDS.SUBSCRIPTIONS),
  rule('notion',            CAT_IDS.SUBSCRIPTIONS),
  rule('paypal *nba',       CAT_IDS.SUBSCRIPTIONS),
  rule('paypal *netflix',   CAT_IDS.SUBSCRIPTIONS),
  rule('paypal *spotify',   CAT_IDS.SUBSCRIPTIONS),

  // ── Dining Out / Takeaway ──────────────────────────────────────────────────
  rule('starbucks',         CAT_IDS.FOOD_DINING),
  rule('costa',             CAT_IDS.FOOD_DINING),
  rule('gong cha',          CAT_IDS.FOOD_DINING),
  rule('st. ali',           CAT_IDS.FOOD_DINING),
  rule('deliveroo',         CAT_IDS.FOOD_DINING),
  rule('uber eats',         CAT_IDS.FOOD_DINING),
  rule('just eat',          CAT_IDS.FOOD_DINING),
  rule('mcdonald',          CAT_IDS.FOOD_DINING),
  rule('nandos',            CAT_IDS.FOOD_DINING),
  rule('kfc',               CAT_IDS.FOOD_DINING),
  rule('burger king',       CAT_IDS.FOOD_DINING),
  rule('pret a manger',     CAT_IDS.FOOD_DINING),
  rule('subway',            CAT_IDS.FOOD_DINING),
  rule('pizza hut',         CAT_IDS.FOOD_DINING),
  rule('dominos',           CAT_IDS.FOOD_DINING),
  rule('wagamama',          CAT_IDS.FOOD_DINING),
  rule('itsu',              CAT_IDS.FOOD_DINING),
  rule('400 gradi',         CAT_IDS.FOOD_DINING),
  rule('mister fox',        CAT_IDS.FOOD_DINING),
  rule('gyg',               CAT_IDS.FOOD_DINING),
  rule('hot star',          CAT_IDS.FOOD_DINING),
  rule('fragrant harbour',  CAT_IDS.FOOD_DINING),
  rule('hungry jacks',      CAT_IDS.FOOD_DINING),
  rule('oporto',            CAT_IDS.FOOD_DINING),
  rule('domino',            CAT_IDS.FOOD_DINING),
  rule('red rooster',       CAT_IDS.FOOD_DINING),
  rule('sq *foodness',      CAT_IDS.FOOD_DINING),
  rule('zlr*maguro',        CAT_IDS.FOOD_DINING),
  rule('the sy he group',   CAT_IDS.FOOD_DINING),
  rule('hhj investment',    CAT_IDS.FOOD_DINING),
  rule('rwq* goodbean',     CAT_IDS.FOOD_DINING),
  rule('rwd* goodbean',     CAT_IDS.FOOD_DINING),
  rule('natures green farm',CAT_IDS.FOOD_DINING),

  // ── Groceries ──────────────────────────────────────────────────────────────
  rule('tesco',                  CAT_IDS.FOOD_GROCERIES),
  rule('sainsbury',              CAT_IDS.FOOD_GROCERIES),
  rule('waitrose',               CAT_IDS.FOOD_GROCERIES),
  rule('asda',                   CAT_IDS.FOOD_GROCERIES),
  rule('aldi',                   CAT_IDS.FOOD_GROCERIES),
  rule('lidl',                   CAT_IDS.FOOD_GROCERIES),
  rule('morrisons',              CAT_IDS.FOOD_GROCERIES),
  rule('marks & spencer food',   CAT_IDS.FOOD_GROCERIES),
  rule('m&s food',               CAT_IDS.FOOD_GROCERIES),
  rule('co-op',                  CAT_IDS.FOOD_GROCERIES),
  rule('ocado',                  CAT_IDS.FOOD_GROCERIES),
  rule('amazon fresh',           CAT_IDS.FOOD_GROCERIES),
  rule('woolworths',             CAT_IDS.FOOD_GROCERIES),
  rule('coles',                  CAT_IDS.FOOD_GROCERIES),
  rule('costco',                 CAT_IDS.FOOD_GROCERIES),
  rule('aldi stores',            CAT_IDS.FOOD_GROCERIES),
  rule('iga',                    CAT_IDS.FOOD_GROCERIES),
  rule('harris farm',            CAT_IDS.FOOD_GROCERIES),
  rule('drakes supermarket',     CAT_IDS.FOOD_GROCERIES),
  rule('foodworks',              CAT_IDS.FOOD_GROCERIES),
  rule('fengsheng supermarket',  CAT_IDS.FOOD_GROCERIES),
  rule('direcfresh foods',       CAT_IDS.FOOD_GROCERIES),
  rule('afc knox',               CAT_IDS.FOOD_GROCERIES),

  // ── Utilities: Electricity ─────────────────────────────────────────────────
  rule('british gas',      CAT_IDS.UTILITIES_ELECTRICITY),
  rule('eon',              CAT_IDS.UTILITIES_ELECTRICITY),
  rule('octopus energy',   CAT_IDS.UTILITIES_ELECTRICITY),
  rule('edf',              CAT_IDS.UTILITIES_ELECTRICITY),
  rule('origin energy',    CAT_IDS.UTILITIES_ELECTRICITY),
  rule('energyaustralia',  CAT_IDS.UTILITIES_ELECTRICITY),
  rule('agl',              CAT_IDS.UTILITIES_ELECTRICITY),
  rule('dodo power',       CAT_IDS.UTILITIES_ELECTRICITY),

  // ── Utilities: Gas ─────────────────────────────────────────────────────────
  rule('dodo services',    CAT_IDS.UTILITIES_GAS),

  // ── Utilities: Water ───────────────────────────────────────────────────────
  rule('thames water',       CAT_IDS.UTILITIES_WATER),
  rule('south east water',   CAT_IDS.UTILITIES_WATER),
  rule('sydney water',       CAT_IDS.UTILITIES_WATER),
  rule('yarra valley water', CAT_IDS.UTILITIES_WATER),

  // ── Utilities: Internet ────────────────────────────────────────────────────
  rule('virgin media',      CAT_IDS.UTILITIES_INTERNET),
  rule('bt internet',       CAT_IDS.UTILITIES_INTERNET),
  rule('sky broadband',     CAT_IDS.UTILITIES_INTERNET),
  rule('aussie broadband',  CAT_IDS.UTILITIES_INTERNET),

  // ── Utilities: Phone ───────────────────────────────────────────────────────
  rule('vodafone',   CAT_IDS.UTILITIES_PHONE),
  rule('ee limited', CAT_IDS.UTILITIES_PHONE),
  rule('o2',         CAT_IDS.UTILITIES_PHONE),
  rule('three',      CAT_IDS.UTILITIES_PHONE),
  rule('optus',      CAT_IDS.UTILITIES_PHONE),
  rule('telstra',    CAT_IDS.UTILITIES_PHONE),
  rule('belong',     CAT_IDS.UTILITIES_PHONE),

  // ── Insurance: Health ──────────────────────────────────────────────────────
  rule('medibank',   CAT_IDS.INSURANCE_HEALTH),
  rule('bupa au',    CAT_IDS.INSURANCE_HEALTH),
  rule('bupa',       CAT_IDS.INSURANCE_HEALTH),
  rule('hcf',        CAT_IDS.INSURANCE_HEALTH),
  rule('nib health', CAT_IDS.INSURANCE_HEALTH),
  rule('axa health', CAT_IDS.INSURANCE_HEALTH),
  rule('vitality',   CAT_IDS.INSURANCE_HEALTH),

  // ── Insurance: Pet ────────────────────────────────────────────────────────
  rule('pet insurance', CAT_IDS.INSURANCE_PET),

  // ── Bills ──────────────────────────────────────────────────────────────────
  rule('bpayn deft payments',     CAT_IDS.BILLS_BODY_CORP),
  rule('bpayn knox city council', CAT_IDS.BILLS_COUNCIL),

  // ── Health & Wellbeing ─────────────────────────────────────────────────────
  rule('chemist warehouse',    CAT_IDS.HEALTH),
  rule('lloyds pharmacy',      CAT_IDS.HEALTH),
  rule('pharmacy',             CAT_IDS.HEALTH),
  rule('pline pharm',          CAT_IDS.HEALTH),
  rule('pline ph ',            CAT_IDS.HEALTH),
  rule('pharmacy 4 less',      CAT_IDS.HEALTH),
  rule('bayswater nth pharm',  CAT_IDS.HEALTH),
  rule('cwh forest hill',      CAT_IDS.HEALTH),
  rule('boots',                CAT_IDS.HEALTH),
  rule('dentist',              CAT_IDS.HEALTH),
  rule('nhs',                  CAT_IDS.HEALTH),
  rule('optical',              CAT_IDS.HEALTH),
  rule('specsavers',           CAT_IDS.HEALTH),
  rule('pelvic strength physio',CAT_IDS.HEALTH),
  rule('eastern health',       CAT_IDS.HEALTH),
  rule('cdc boronia',          CAT_IDS.HEALTH),
  rule('gym',                  CAT_IDS.HEALTH),
  rule('puregym',              CAT_IDS.HEALTH),
  rule('david lloyd',          CAT_IDS.HEALTH),
  rule('virgin active',        CAT_IDS.HEALTH),
  rule('anytime fitness',      CAT_IDS.HEALTH),
  rule('peloton',              CAT_IDS.HEALTH),
  rule('classpass',            CAT_IDS.HEALTH),
  rule('crzyoga',              CAT_IDS.HEALTH),
  rule('yoga',                 CAT_IDS.HEALTH),
  rule('f45',                  CAT_IDS.HEALTH),
  rule('snap fitness',         CAT_IDS.HEALTH),
  rule('goodlife',             CAT_IDS.HEALTH),
  rule('fitness first',        CAT_IDS.HEALTH),
  rule('my place massage',     CAT_IDS.HEALTH),

  // ── Health & Wellbeing: Beauty ─────────────────────────────────────────────
  rule('sns exclusive salon',  CAT_IDS.HEALTH_BEAUTY),
  rule('mao feng',             CAT_IDS.HEALTH_BEAUTY),
  rule('j and lg',             CAT_IDS.HEALTH_BEAUTY),
  rule('salon de j',           CAT_IDS.HEALTH_BEAUTY),
  rule('sq *orange hair',      CAT_IDS.HEALTH_BEAUTY),
  rule('white ivy',            CAT_IDS.HEALTH_BEAUTY),
  rule('alana taylor',         CAT_IDS.HEALTH_BEAUTY),

  // ── Travel ─────────────────────────────────────────────────────────────────
  rule('easyjet',          CAT_IDS.TRAVEL),
  rule('ryanair',          CAT_IDS.TRAVEL),
  rule('british airways',  CAT_IDS.TRAVEL),
  rule('qantas',           CAT_IDS.TRAVEL),
  rule('virgin australia', CAT_IDS.TRAVEL),
  rule('jetstar',          CAT_IDS.TRAVEL),
  rule('enterprise car',   CAT_IDS.TRAVEL),
  rule('hertz',            CAT_IDS.TRAVEL),
  rule('avis',             CAT_IDS.TRAVEL),

  // ── Shopping ───────────────────────────────────────────────────────────────
  rule('amazon',              CAT_IDS.SHOPPING),
  rule('ebay',                CAT_IDS.SHOPPING),
  rule('amazon au',           CAT_IDS.SHOPPING),
  rule('amazon marketplace',  CAT_IDS.SHOPPING),
  rule('paypal *ebay',        CAT_IDS.SHOPPING),
  rule('paypal *isiptrading', CAT_IDS.SHOPPING),
  rule('temu',                CAT_IDS.SHOPPING),
  rule('sq *the lorri',       CAT_IDS.SHOPPING),
  rule('westfield',           CAT_IDS.SHOPPING),
  rule('kmart',               CAT_IDS.SHOPPING),
  rule('target',              CAT_IDS.SHOPPING),
  rule('big w',               CAT_IDS.SHOPPING),
  rule('asos',                CAT_IDS.SHOPPING),
  rule('zara',                CAT_IDS.SHOPPING),
  rule('h&m',                 CAT_IDS.SHOPPING),
  rule('primark',             CAT_IDS.SHOPPING),
  rule('next',                CAT_IDS.SHOPPING),
  rule('the iconic',          CAT_IDS.SHOPPING),
  rule('uniqlo',              CAT_IDS.SHOPPING),
  rule('cotton on',           CAT_IDS.SHOPPING),
  rule('country road',        CAT_IDS.SHOPPING),
  rule('peter alexander',     CAT_IDS.SHOPPING),
  rule('best & less',         CAT_IDS.SHOPPING),
  rule('best and less',       CAT_IDS.SHOPPING),
  rule('myer',                CAT_IDS.SHOPPING),
  rule('david jones',         CAT_IDS.SHOPPING),
  rule('john lewis',          CAT_IDS.SHOPPING),
  rule('marks & spencer',     CAT_IDS.SHOPPING),
  rule('argos',               CAT_IDS.SHOPPING),
  rule('ikea',                CAT_IDS.SHOPPING),
  rule('baby bunting',        CAT_IDS.SHOPPING),
  rule('paws n stuff',        CAT_IDS.SHOPPING),
  rule('budgetpetprodu',      CAT_IDS.SHOPPING),
  rule('paypal *budgetpetpr', CAT_IDS.SHOPPING),
  rule('pet circle',          CAT_IDS.SHOPPING),
  rule('petbarn',             CAT_IDS.SHOPPING),
  rule('animates',            CAT_IDS.SHOPPING),
  rule('hoyts',               CAT_IDS.SHOPPING),
  rule('village cinemas',     CAT_IDS.SHOPPING),
  rule('event cinemas',       CAT_IDS.SHOPPING),
  rule('lup tix',             CAT_IDS.SHOPPING),
  rule('ticketek',            CAT_IDS.SHOPPING),
  rule('ticketmaster',        CAT_IDS.SHOPPING),
  rule('melbourn conventon',  CAT_IDS.SHOPPING),
  rule('baby sensory',        CAT_IDS.SHOPPING),
];
